"""Static review pages: fake data, real sprites; no production scene imports."""
from pathlib import Path
import json
P=Path(__file__).parent
icons={
 'close':'M6 6l12 12M18 6L6 18', 'menu':'M4 6h16M4 12h16M4 18h16',
 'team':'M8 11a3 3 0 1 0 0-6 3 3 0 0 0 0 6M2 20v-3c0-5 12-5 12 0v3M16 5a3 3 0 0 1 0 6M17 14c4 0 5 2 5 6',
 'map':'M3 5l6-2 6 2 6-2v16l-6 2-6-2-6 2zM9 3v16M15 5v16',
 'bag':'M5 7h14l2 14H3zM8 7V5a4 4 0 0 1 8 0v2',
 'missions':'M6 3h12v18H6zM9 8h6M9 12h6M9 16h4',
 'dex':'M4 3h16v18H4zM8 3v18M11 8h6M11 12h6',
 'more':'M5 12h1M11 12h1M17 12h1', 'run':'M5 5l7 7-7 7M12 5l7 7-7 7',
 'attack':'M5 20L20 5V2h-3L2 17M4 13l7 7M3 21l3-3',
 'swap':'M3 7h16l-4-4M21 17H5l4 4', 'ballot':'M8 3h8v8H8zM4 10l-2 4v7h20v-7l-2-4M7 14h10',
 'star':'M12 2l3 6 7 1-5 5 1 7-6-3-6 3 1-7-5-5 7-1z',
 'flag':'M5 22V3h14l-3 5 3 5H5', 'coin':'M17 5H9l-3 7 3 7h8M3 10h11M3 14h11',
 'poll':'M4 20V12M11 20V7M18 20V3', 'heal':'M9 3h6v6h6v6h-6v6H9v-6H3V9h6z',
 'tool':'M15 3a6 6 0 0 0-7 7L2 16l6 6 6-6a6 6 0 0 0 7-7l-5 4-5-5z',
 'key':'M9 13a5 5 0 1 1 0-10 5 5 0 0 1 0 10M13 11l9 9M17 15l3-3',
 'arrow':'M4 12h16M14 6l6 6-6 6', 'zoom':'M10 4a6 6 0 1 0 0 12 6 6 0 0 0 0-12M15 15l6 6M7 10h6M10 7v6',
}
def ico(n):return f'<svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><path d="{icons[n]}"/></svg>'
def img(id,cls='',kind='monsters'):return f'<img class="pixel {cls}" src="/sprites/{kind}/{id}.png" alt="">'
def button(body,label='',cls='',attrs=''):return f'<button class="{cls}"'+(f' aria-label="{label}"' if label else '')+f' {attrs}>{body}</button>'
def badge(t):return f'<img class="type" src="/sprites/ui/type_{t}.png" alt="{t.capitalize()}">'
def hp(v,maxv,preview=None):return f'<span class="hp" role="meter" aria-label="Punti vita" aria-valuenow="{v}" aria-valuemin="0" aria-valuemax="{maxv}"><i style="width:{v/maxv*100}%"></i>'+ (f'<i class="gain" style="left:{v/maxv*100}%;width:{(preview-v)/maxv*100}%"></i>' if preview else '')+'</span>'
def header(title):return '<header class="heading"><h1>'+title+'</h1>'+button(ico('close'),'Chiudi','close','data-close')+'</header>'
mons=[('berlusconix','BERLUSCONIX',26,64,102,'media','destra'),('movimenton','MOVIMENTON',26,103,103,'istituzione',''),('mediocrate','MEDIOCRATE',17,65,65,'media',''),('giorgiagon','GIORGIAGON',24,72,88,'destra',''),('draghimon','DRAGHIMON',23,20,94,'tecno','istituzione'),('ellyna','ELLYNA',22,0,81,'sinistra','')]
def member(m,i,mini=False):
 id,name,lv,v,mx,t,t2=m
 if mini:return button(img(id)+hp(v,mx,min(mx,v+round(mx*.3)) if v and v<mx else None)+(f'<span class="gain-label">+{min(mx-v,round(mx*.3))}</span>' if v and v<mx else ''),name+' · '+str(v)+' punti vita','recipient'+(' unavailable' if not v or v==mx else ''),'data-recipient')
 return button(('<span class="leader">'+ico('star')+'</span>' if i==0 else '')+img(id,'member-sprite')+f'<span class="member-name display">{name}</span><span class="level">Lv{lv}</span><span class="member-hp">{hp(v,mx)}<span>{v}/{mx}</span></span><span class="types">'+badge(t)+(badge(t2) if t2 else '')+'</span>'+('<span class="stamp ko">KO</span>' if v==0 else ''),f'{name}, livello {lv}, {v} punti vita su {mx}'+(', capofila' if i==0 else ''),'member'+(' selected' if i==0 else '')+' '+('fainted' if not v else ''),'data-link="compagno.html"')
def move(name,pp,t='media',eff='',extra=''):
 return button(f'<strong class="display">{"APPELLO" if name == "APPELLO AGLI ALLEATI" else name}</strong><span class="move-meta">{badge(t)}<span>{pp}</span><span class="eff">{eff}</span></span>',name+' · '+pp+' PP','move '+t+(' exhausted' if pp.startswith('0/') else ''),f'data-move="{name}" '+extra)
def world():
 trees=''.join(img('tree','tree', 'tiles').replace('class="pixel tree"',f'class="pixel tree" style="left:{x}px;top:{y}px"') for x,y in [(x,y) for y in [0,96,192,960,1056] for x in range(0,960,96)]+[(x,y) for x in [0,96,768,864] for y in range(288,960,96)])
 return '<div class="world" data-world><div class="world-art"><div class="road vertical"></div><div class="road crossing"></div><div class="pond"></div><div class="tallgrass"></div>'+trees+img('build_house_front_red','house','tiles')+img('obj_bench','bench','tiles')+img('obj_flowers','flowers','tiles')+'</div>'+img('player_south','player','chars')+img('npc_journalist_west','npc','chars')+'</div>'
def world_ui(active=True):return '<div class="world-top"><span class="location tag">PERCORSO 1</span><nav class="quick">'+''.join(button(ico(ic),label,'icon-button',f'data-link="{dest}.html"') for ic,label,dest in [('team','Squadra','squadra'),('map','Mappa','mappa'),('menu','Menù','menu')])+'</nav></div>'+button('<span>›</span> Sfida lo Studio 5','Ripiega obiettivo','objective','data-collapse')+'<div class="stick" aria-hidden="true"><i></i></div><div class="world-actions">'+(button('<b>A</b><span>Parla</span>','Parla','talk','data-link="dialogo.html"') if active else '')+button(ico('run'),'Attiva corsa','run icon-button','data-run')+'</div>'
scenes={}
scenes['esplorazione']=world()+world_ui(True)
scenes['esplorazione-orizzontale']=world()+world_ui(False)
foe=f'<div class="combat-tag foe-tag"><strong class="display">BERLUSCONIX</strong><span>Lv26</span>{hp(68,102)}</div>'
ally=f'<div class="combat-tag ally-tag"><strong class="display">MEDIOCRATE</strong><span>Lv17</span>{hp(65,65)}<span class="hp-number">65/65</span><span class="resource" aria-label="Polemica: due su tre">● ● ○</span></div>'
scenes['lotta']='<div class="battle-scene" data-battle-scene>'+foe+button(ico('attack'),'Intenzione: attacco','intent','data-detail="Attacco annunciato"')+img('berlusconix','foe battle-sprite')+img('mediocrate','ally battle-sprite')+ally+'</div><div class="battle-controls"><div class="chronicle">Mediocrate usa Conferenza stampa!</div><div class="moves-grid">'+''.join([move('TELEPROMESSA','14/15'),move('APPELLO AGLI ALLEATI','15/15',eff='▲'),move('EDITORIALE','9/10',eff='▲'),move('BUNGA PARTY','0/5',eff='▲')])+'</div><nav class="battle-actions">'+''.join(button(ico(ic)+f'<span>{label}</span>',label,'secondary',f'data-link="{dest}.html"' if dest else 'data-detail="Dossier · Fuga"') for ic,label,dest in [('swap','Cambio','squadra'),('bag','Borsa','borsa'),('ballot','Recluta',''),('more','Altro','')])+'</nav></div>'
scenes['squadra']=header('SQUADRA')+'<div class="team-list">'+''.join(member(m,i) for i,m in enumerate(mons))+'</div>'
profile='<section class="profile-hero">'+img('berlusconix','profile-sprite')+'<div><h1>BERLUSCONIX</h1><span>Lv26</span><span class="types">'+badge('media')+badge('destra')+'</span>'+hp(64,102)+'<span>64/102</span></div><span class="stamp">ELETTO</span></section>'
profile_tabs='<nav class="tabs">'+''.join(button(t,cls='active' if i==0 else '',attrs=f'data-tab="{id}"') for i,(t,id) in enumerate([('Mosse','moves'),('Valori','values'),('Storia','story')]))+'</nav>'
scenes['compagno']='<div class="profile-close">'+button(ico('close'),'Chiudi','close','data-close')+'</div>'+profile+profile_tabs+'<div class="tab-page move-list" id="moves">'+''.join([move('TELEPROMESSA','14/15'),move('APPELLO AGLI ALLEATI','15/15',eff='▲'),move('EDITORIALE','9/10',eff='▲'),move('BUNGA PARTY','0/5')])+'</div><div class="tab-page stats" id="values" hidden>'+''.join(f'<div><span>{n}</span><span class="stat-bar"><i style="width:{v}%"></i></span><b>{v}</b></div>' for n,v in [('Retorica',68),('Faccia tosta',92),('Carisma',85),('Opportunismo',74)])+'</div><div class="tab-page story" id="story" hidden><h2>Il palinsesto è suo.</h2><p>Promette una replica di tutto, tranne delle domande scomode.</p><h2>Teflon</h2><p>Gli scandali non lasciano il segno.</p><div class="evolution">'+img('telecrate')+ico('arrow')+img('berlusconix')+'</div></div>'
items=[('caffe','Caffè',11),('spritz','Spritz',6),('mojito','Mojito',3),('maalox','Maalox',4),('caffettiera','Caffettiera',2),('caffe','Caffè lungo',5),('caffe','Doppio',1),('maalox','Maalox forte',2)]
scenes['borsa']=header('BORSA')+'<nav class="tabs bag-tabs">'+''.join(button(ico(ic)+f'<span>{n}</span>',cls='active' if i==0 else '',attrs='data-bag-tab') for i,(ic,n) in enumerate([('heal','Cure'),('ballot','Schede'),('tool','Strumenti'),('key','Chiave')]))+'</nav><div class="item-grid">'+''.join(button(img(id,kind='items')+f'<strong>{name}</strong><span>×{count}</span>',name+' · quantità '+str(count),'item','data-item="'+name+'"') for id,name,count in items)+'</div><div class="sheet-shade" id="item-sheet" hidden><section class="bottom-sheet"><header><h2>Caffè del bar sport</h2>'+button(ico('close'),'Chiudi oggetto','close','data-dismiss')+'</header><p>Recupera il 30% dei PV.</p><div class="recipient-row">'+''.join(member(m,i,True) for i,m in enumerate(mons))+'</div></section></div>'
map_svg='''<svg class="italietta" viewBox="0 0 412 760" role="img" aria-label="Mappa illustrata dell’Italietta"><defs><pattern id="sea" width="24" height="24" patternUnits="userSpaceOnUse"><path d="M0 12q6-5 12 0t12 0" fill="none" stroke="#F4EEDC" opacity=".2"/></pattern></defs><rect width="412" height="760" fill="#1E3A8A"/><rect width="412" height="760" fill="url(#sea)"/><path d="M45 130l40-48 48 25 38-30 50 30 61-5 18 33-40 36-34 7-12 39 20 28 10 63 36 40 30 38 42 17 16 29-43 3-27-33-27-9 9 48 26 52-12 38-29-14-6-36-37-16-42-72-25-23-19-52-25-31-27-83-27-16-28 7-25-36z" fill="#E4DAC0" stroke="#14161F" stroke-width="4"/><path d="M265 598l-70-15-35 26 30 28 46 8zM79 449l-27 31 7 60 24-2 17-48z" fill="#E4DAC0" stroke="#14161F" stroke-width="4"/><path d="M95 161q54 7 87 52t28 74 39 66 39 90" fill="none" stroke="#D7263D" stroke-width="5" stroke-dasharray="7 5"/><g fill="#1B998B" stroke="#14161F" stroke-width="2"><path d="M76 127l13-22 14 22zM112 148l15-27 16 27zM189 291l13-22 14 22zM226 358l13-22 14 22z"/></g><g fill="#14161F" font-family="Barlow" font-size="20"><text x="48" y="74">NORD</text><text x="284" y="185" fill="#F4EEDC">ADRIATICO</text><text x="48" y="385" fill="#F4EEDC">TIRRENO</text></g><g fill="#FFD23F" stroke="#14161F" stroke-width="3"><circle cx="95" cy="161" r="8"/><circle cx="182" cy="213" r="8"/><circle cx="210" cy="287" r="8"/><circle cx="249" cy="353" r="8"/><circle cx="288" cy="443" r="8"/></g></svg>'''
scenes['mappa']=header('ITALIETTA')+'<nav class="tabs map-tabs">'+''.join(button(n,cls='active' if i==0 else '',attrs='data-map-tab') for i,n in enumerate(['Italietta','Rotte','Atto 3']))+'</nav><div class="map-art"><div class="map-world">'+map_svg+'<div class="map-label borgo">Borgo Urne</div><div class="map-label medio">Mediopoli</div>'+button(ico('flag')+'<span>Studio 5</span>','Studio 5 · prossima tappa','map-pin','data-place')+button('<span class="here-dot"></span>','La tua posizione: Percorso 1','map-here','data-place')+'</div>'+button(ico('zoom'),'Cambia zoom mappa','map-zoom','data-zoom')+'</div><div class="sheet-shade" id="place-sheet" hidden><section class="bottom-sheet"><header><h2>Studio 5</h2>'+button(ico('close'),'Chiudi luogo','close','data-dismiss')+'</header><p>Il dibattito comincia dopo la pubblicità.</p>'+button('Viaggia · 80 €','Viaggia allo Studio 5 per 80 euro','primary','data-dismiss')+'</section></div>'
scenes['impara']=header('NUOVA MOSSA')+'<div class="learn-hero">'+img('movimenton')+'<strong class="display">MOVIMENTON</strong><span>Lv26</span></div><div class="new-move"><span class="stamp">NUOVA</span>'+move('VOTO DI FIDUCIA','20/20','istituzione')+'</div><div class="learn-list">'+''.join([move('COMIZIO','20/25','populismo'),move('SLOGAN','15/15','populismo'),move('GIRAVOLTA','12/15','centro'),move('QUORUM','10/10','istituzione')])+'</div>'+button('Non imparare',cls='decline',attrs='data-close')
scenes['menu']=world()+'<div class="veil"></div><section class="pause-sheet"><header><h1>IN PAUSA</h1>'+button(ico('close'),'Chiudi menù','close','data-close')+'</header><div class="campaign-strip"><span>'+ico('coin')+' 9.320 €</span><span>'+ico('poll')+' 100%</span></div><nav class="menu-grid">'+''.join(button(ico(ic)+f'<strong>{n}</strong>',n,'menu-entry',f'data-link="{dest}.html"') for ic,n,dest in [('team','Squadra','squadra'),('bag','Borsa','borsa'),('missions','Missioni','esplorazione'),('map','Mappa','mappa'),('dex','Politicdex','compagno'),('more','Altro','esplorazione')])+'</nav><div class="paper-edge"></div></section>'
scenes['dialogo']=world()+'<div class="dialog-choices">'+button('Fammi una domanda.',cls='choice',attrs='data-choice')+button('Passo oltre.',cls='choice',attrs='data-close')+'</div><section class="dialog-box"><span class="speaker tag">MARA · CRONISTA</span>'+img('npc_journalist_south','portrait','chars')+'<p>«Una promessa in tre parole.<br>La quarta la paghiamo noi.»</p>'+button('▸','Continua','continue','data-choice')+'</section>'
for id,content in scenes.items():
 (P/(id+'.html')).write_text('<!doctype html><html lang="it"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>Tribuna elettorale · '+id+'</title><link rel="stylesheet" href="mock.css"></head><body class="'+id+'"><main class="screen" data-screen="'+id+'">'+content+'</main><dialog id="detail"><header><h2>Dettaglio mossa</h2>'+button(ico('close'),'Chiudi dettaglio','close','data-dismiss')+'</header><p>Potenza 70 · Precisione 100%</p><p>Colpisce prima. Danno stimato: 81–92 PV.</p></dialog><script src="mock.js"></script></body></html>')
(P/'manifest.json').write_text(json.dumps(list(scenes),indent=2))
